GRID_W, GRID_H = 40, 35
CELL_SIZE = 25

SIDEBAR_W = 300

TOP_BAR_H = 50
BOTTOM_BAR_H = 100
MAP_OFFSET_Y = TOP_BAR_H

SCREEN_W = GRID_W * CELL_SIZE + SIDEBAR_W
SCREEN_H = TOP_BAR_H + GRID_H * CELL_SIZE + BOTTOM_BAR_H

FPS = 10
TICKS_PER_PHASE = 20

RANDOM_SEED = 42

MAX_SNAPSHOTS = None
